#!/bin/bash

# clean current files
rm -rf ./css ./js ./index.html

# bring in latest changes from master
git merge master -m "merge master"

# build it
./scripts/build

# copy build artifacts
cp -r resources/public/* .

# save changes
git add . && git commit -m "fresh build"

# publish
git push
